### ISSUE TITLE
Accept POJO for image options and convert to query string

### ISSUE THREAD

**Issue by redoPop** [tedconf/js-crushinator-helpers#3]
Currently, the helper's second parameter (options) must be a string, which is appended directly to the crushinator URL as its query parameters:

```javascript
crush('http://images.ted.com/image.jpg', 'w=320')
  // => 'https://tedcdnpi-a.akamaihd.net/r/images.ted.com/image.jpg?w=320'
```

It would be better to pass options to the helper in a POJO:

```javascript
crush('http://images.ted.com/image.jpg', { width: 320 })
  // => 'https://tedcdnpi-a.akamaihd.net/r/images.ted.com/image.jpg?w=320'
```

Advantages:

* We can easily protect against XSS (via `encodeURIComponent` etc.)
* Property names can be a little longer, communicating their purpose more clearly.
* Gives us a better path to renaming or deprecating individual options in future.

**Comment by redoPop** [comment]
Looking at Crushinator's current options, the following seem like obvious abstractions:

| Helper property       | Query parameter | Description
| :-------------------- | :-------------- | :--------------------
| `width`               | `w`             | Target image width in pixels. (Actual image dimensions will vary with geometry.)
| `height`              | `h`             | Target image height in pixels. (Actual image dimensions will vary with geometry.)
| \* `geometry`         | `op`            | Geometry qualifier to use during resizing (see description below).
| `quality`             | `quality`       | Image quality as a percentage (0-100). Defaults to 75 if unspecified.

**Geometry** is an odd one: the Crushinator API expects one of [the 6 character qualifiers used by GraphicsMagick](http://www.graphicsmagick.org/Magick++/Geometry.html#graphicsmagick-extensions-to-x11-geometry-specifications) (`%`, `!`, `<`, `>`, `@`, `^`), defaulting to `>` if none is specified. To be honest I've never found any of these options more useful than the default. I'd like to leave the geometry/`op` parameter out of the helper's API until we have actual need of it.

**Cropping** can be done before or after an image is resized (_before_ resize via the `precrop` query parameter, and _after_ resize via the `c` parameter). In both cases, the query parameter is either 2 or 4 comma-separated numbers indicating the crop width and height in pixels (as the first two numbers) and optionally x and y coordinates at which the crop should start. I think it makes most sense to accept crop configurations as their own POJO; e.g. `crop: { width: 100, height: 100, x: 5, y: 50 }`.

We're also planning to introduce an unsharp parameter, with tunable radius, sigma, amount, and threshold settings. As with the crop configuration, I think it makes sense to accept these values in their own POJO.

**Comment by redoPop** [comment]
I'd like to use a boolean `afterResize` to help distinguish pre-resize crop from post-resize crop (i.e., cropping that happens to the image before vs. after resizing it), which can be added to the crop options like so:

```javascript
crush('http://images.ted.com/image.jpg', {
  crop: {
    width: 100, height: 100,   // crop size
    x: 50, y: 50,              // crop coordinates
    afterResize: true          // crop
  }
})
```

The default behavior would crop the original image (i.e. produce a Crushinator URL using the `precrop` query param), and the `afterResize` would cause it to crop the resized version of the image (the `c` query param).

**Comment by alexdean** [comment]
What do you think about trying to keep the APIs for the JS & [rails helpers](https://github.com/tedconf/crushinator_helpers/blob/master/app/helpers/crushinator_helpers/view_helpers.rb#L4) roughly similar?

Maybe it's not a big deal if their feature sets diverge, but at first glace it seems like we ought to keep them somewhat aligned. What do you think?

**Comment by redoPop** [comment]
Definitely!

We have a slightly more urgent need for this in the JS helper since we're currently relying on a naive (potentially XSS-vulnerable) string append, and we have no support for providing Crushinator options in hash/object form.

In the Rails helper we take an options hash and apply `.to_query`, solving at least these two problems. However, the Rails helper could still benefit from having an internally whitelisted / helper-specific API, and we should look at implementing it there too.

**Comment by redoPop** [comment]
I can't think of any query string semantics that can't be represented in object form. Which means we could address this by accepting an options POJO that can potentially contain both the helper-specific API options and plain old query parameters, e.g.:

```javascript
crushinator.crush('http://images.ted.com/image.jpg', {
    width: 320,   // JS helper API
    height: 240,  // JS helper API
    c: '200,100'  // Plain old query param
  })
  // => 'https://tedcdnpi-a.akamaihd.net/r/images.ted.com/image.jpg?w=320&h=240&c=200,100'
```

In the current codebase, the "c" property would be ignored because it isn't one pf the vetted API options.
